version: "2.0"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  dotnetmetricsapi:
    image: eduardobueno75/dotnetmetrics:latest
    container_name: dotnetmetricsapi
    ports:
      - 8080:80
    networks:
      - dotnetmetrics

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - dotnetmetrics

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dotnetmetrics

networks:
    dotnetmetrics:
      driver: bridge