version: "1.0"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - dotnetmetrics

networks:
    dotnetmetrics:
      driver: bridge